'use client';

import { motion } from 'framer-motion';
import {
    Search,
    Edit3,
    Share2,
    TrendingUp,
    Bot,
    BarChart3,
    Palette,
    Zap,
    ArrowRight,
    Cpu,
    CheckCircle2,
    Globe
} from 'lucide-react';
import Link from 'next/link';

const expertiseCategories = [
    {
        id: 'seo',
        title: 'AI-Powered SEO & Search Systems',
        icon: Search,
        color: 'text-blue-600',
        bgColor: 'bg-blue-50',
        skills: [
            'AI keyword research & clustering',
            'Search intent analysis using AI',
            'AI-based content gap analysis',
            'Automated on-page SEO optimization',
            'AI internal linking suggestions',
            'SERP competitor analysis with AI',
            'Predictive ranking opportunity analysis',
            'AI meta title & description optimization',
            'AI schema markup generation',
            'SEO content briefs generated by AI',
            'Semantic Entity Calibration',
            'RAG-driven Authority Mapping'
        ]
    },
    {
        id: 'content',
        title: 'AI Content & Narrative Marketing',
        icon: Edit3,
        color: 'text-rose-600',
        bgColor: 'bg-rose-50',
        skills: [
            'AI blog writing (SEO optimized)',
            'AI landing page copywriting',
            'AI sales page copy',
            'AI email marketing copy',
            'AI product descriptions',
            'AI video script writing',
            'AI webinar script writing',
            'AI content repurposing (Blog → Social)',
            'AI content calendar planning',
            'AI headline & hook optimization',
            'Chef vs DJ Narrative Drafting'
        ]
    },
    {
        id: 'social',
        title: 'AI Social & Viral Ecosystems',
        icon: Share2,
        color: 'text-indigo-600',
        bgColor: 'bg-indigo-50',
        skills: [
            'AI social media post creation',
            'AI caption & hashtag generation',
            'AI reel & short video script ideas',
            'AI content trend analysis',
            'AI audience behavior analysis',
            'AI engagement prediction',
            'AI DM automation setup',
            'AI comment auto-response systems',
            'AI influencer identification',
            'AI social media ad copy testing'
        ]
    },
    {
        id: 'ads',
        title: 'AI Performance & Paid Ad Architectures',
        icon: TrendingUp,
        color: 'text-emerald-600',
        bgColor: 'bg-emerald-50',
        skills: [
            'AI ad copy variations generation',
            'AI A/B testing automation',
            'AI audience targeting optimization',
            'Predictive ad budget allocation',
            'AI conversion rate optimization',
            'AI landing page heatmap insights',
            'AI retargeting campaign optimization',
            'AI Google Ads automation setup',
            'AI Facebook Ads automation',
            'AI performance forecasting'
        ]
    },
    {
        id: 'automation',
        title: 'AI Automation & Conversational Funnels',
        icon: Bot,
        color: 'text-brand-blue',
        bgColor: 'bg-blue-50/50',
        skills: [
            'AI chatbot setup for websites',
            'AI WhatsApp automation for leads',
            'AI lead scoring system',
            'AI CRM automation',
            'AI follow-up email automation',
            'AI appointment booking automation',
            'AI pipeline prediction',
            'AI abandoned cart recovery systems',
            'AI conversational funnels',
            'AI sales assistant bots'
        ]
    },
    {
        id: 'analytics',
        title: 'AI Intelligence & Predictive Analytics',
        icon: BarChart3,
        color: 'text-amber-600',
        bgColor: 'bg-amber-50',
        skills: [
            'AI business performance dashboards',
            'Predictive sales forecasting',
            'AI customer lifetime value prediction',
            'AI churn prediction',
            'AI marketing ROI analysis',
            'AI competitor tracking dashboards',
            'AI data visualization reports',
            'AI market trend prediction',
            'AI brand sentiment analysis',
            'AI campaign optimization insights'
        ]
    },
    {
        id: 'creative',
        title: 'AI Creative, Media & Brand Design',
        icon: Palette,
        color: 'text-purple-600',
        bgColor: 'bg-purple-50',
        skills: [
            'AI logo concept generation',
            'AI brand identity suggestions',
            'AI color palette strategy',
            'AI ad creative generation',
            'AI video editing automation',
            'AI voice-over generation',
            'AI presentation deck creation',
            'AI product mockups',
            'AI thumbnail optimization',
            'AI image enhancement & backgrounds'
        ]
    },
    {
        id: 'operations',
        title: 'Business Efficiency & Strategic Ops',
        icon: Zap,
        color: 'text-cyan-600',
        bgColor: 'bg-cyan-50',
        skills: [
            'AI scheduling assistant',
            'Automated appointment reminders',
            'Document summarization (PDF/Reports)',
            'OCR text extraction + Categorization',
            'Auto invoice processing',
            'Inventory prediction AI',
            'Expense categorization AI',
            'Workflow automation bots',
            'AI competitor analysis',
            'Keyword research AI assistant'
        ]
    }
];

export default function ExpertisePage() {
    return (
        <main className="min-h-screen bg-white pt-16">
            <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
                {/* Header */}
                <section className="relative py-24 lg:py-32 overflow-hidden">
                    <div className="absolute inset-0 bg-grid-pattern opacity-5"></div>
                    <div className="absolute top-0 left-0 w-full h-full bg-gradient-to-br from-brand-blue/5 via-transparent to-brand-red/5" />
                    <div className="absolute top-1/4 -left-20 w-96 h-96 bg-brand-blue/10 rounded-full blur-[120px] animate-pulse" />
                    <div className="absolute bottom-1/4 -right-20 w-96 h-96 bg-brand-red/10 rounded-full blur-[120px] animate-pulse" />
                    <div className="text-center max-w-4xl mx-auto relative z-10">
                        <motion.div
                            initial={{ opacity: 0, y: 20 }}
                            animate={{ opacity: 1, y: 0 }}
                        >
                            <div className="inline-flex items-center space-x-2 bg-brand-blue/5 text-brand-blue px-5 py-2 rounded-full text-xs font-normal mb-10 border border-brand-blue/10">
                                <div className="w-2 h-2 bg-brand-blue rounded-full animate-pulse" />
                                <span>The Enterprise AI Capability Vault</span>
                            </div>
                        </motion.div>
                        <h1 className="text-5xl sm:text-6xl md:text-7xl lg:text-8xl font-normal text-gray-900 mb-8 leading-tight">
                            Deep AI <span className="text-brand-blue">Expertise.</span>
                        </h1>
                        <p className="text-lg sm:text-xl text-gray-500 max-w-2xl mx-auto font-normal leading-relaxed">
                            Moving beyond basic tools. We deploy 80+ specialized AI systems designed to transform your operations from manual labor to autonomous growth.
                        </p>
                    </div>
                </section>

                {/* Categories Grid */}
                <div className="grid lg:grid-cols-2 gap-8">
                    {expertiseCategories.map((category, idx) => (
                        <motion.div
                            key={idx}
                            initial={{ opacity: 0, y: 30 }}
                            whileInView={{ opacity: 1, y: 0 }}
                            viewport={{ once: true }}
                            transition={{ duration: 0.6, delay: idx * 0.05 }}
                            className="bg-white rounded-[2.5rem] p-10 border border-gray-100 shadow-sm hover:shadow-xl transition-all duration-500 group"
                        >
                            <div className="flex items-center space-x-6 mb-8">
                                <div className={`w-14 h-14 ${category.bgColor} rounded-2xl flex items-center justify-center transition-transform group-hover:rotate-6`}>
                                    <category.icon className={`h-7 w-7 ${category.color}`} />
                                </div>
                                <h2 className="text-2xl font-normal text-gray-900 group-hover:text-brand-blue transition-colors">
                                    {category.title}
                                </h2>
                            </div>

                            <div className="grid sm:grid-cols-2 gap-y-3 gap-x-6">
                                {category.skills.map((skill, sIdx) => (
                                    <div key={sIdx} className="flex items-start space-x-2 group/item">
                                        <div className="mt-2 h-1 w-1 bg-brand-blue rounded-full opacity-30 group-hover/item:opacity-100 transition-opacity flex-shrink-0" />
                                        <span className="text-[13px] text-gray-500 font-normal leading-snug group-hover/item:text-gray-900 transition-colors">
                                            {skill}
                                        </span>
                                    </div>
                                ))}
                            </div>
                        </motion.div>
                    ))}
                </div>

                {/* Strategic Positioning Banner */}
                <motion.div
                    initial={{ opacity: 0, y: 40 }}
                    whileInView={{ opacity: 1, y: 0 }}
                    viewport={{ once: true }}
                    className="mt-24 p-12 bg-gray-900 rounded-[3rem] text-center text-white relative overflow-hidden"
                >
                    <div className="absolute inset-0 bg-brand-blue/10 opacity-20" />
                    <div className="relative z-10 max-w-3xl mx-auto">
                        <h2 className="text-3xl font-normal mb-6 italic tracking-tight text-blue-200">
                            "The world isn't just using AI; it's being rebuilt by it."
                        </h2>
                        <p className="text-lg text-gray-400 font-normal mb-8">
                            We don't just "use" AI. We architect **Autonomous Growth Systems** that out-rank, out-sell, and out-perform traditional agencies by a factor of 10x.
                        </p>
                        <div className="flex flex-wrap justify-center gap-4 text-[11px] font-normal uppercase tracking-widest text-brand-blue bg-white/5 py-4 px-8 rounded-full border border-white/10">
                            <span>Neuro-SEO</span>
                            <span className="opacity-20">•</span>
                            <span>Agentic Ads</span>
                            <span className="opacity-20">•</span>
                            <span>Predictive CRM</span>
                            <span className="opacity-20">•</span>
                            <span>RAG Architectures</span>
                        </div>
                    </div>
                </motion.div>

                {/* Final CTA */}
                <motion.div
                    initial={{ opacity: 0, scale: 0.95 }}
                    whileInView={{ opacity: 1, scale: 1 }}
                    viewport={{ once: true }}
                    className="mt-24 p-16 bg-blue-50/50 rounded-[4rem] border border-blue-100 text-center relative overflow-hidden"
                >
                    <div className="absolute inset-0 bg-grid-pattern opacity-[0.03]" />
                    <div className="relative z-10">
                        <h2 className="text-4xl font-normal text-gray-900 mb-6">Scale Beyond Human Limits</h2>
                        <p className="text-lg text-gray-500 mb-10 max-w-xl mx-auto font-normal">
                            Ready to deploy an autonomous workforce that never sleeps? Let's engineer your custom AI blueprint.
                        </p>
                        <Link
                            href="/contact"
                            className="inline-flex items-center bg-brand-blue text-white px-12 py-5 rounded-2xl hover:brightness-110 transition-all font-normal uppercase tracking-widest text-sm shadow-xl shadow-brand-blue/20"
                        >
                            Sync Your Operations
                            <ArrowRight className="ml-3 h-5 w-5" />
                        </Link>
                    </div>
                </motion.div>
            </div>
        </main>
    );
}
